-- Vanaguide :: core/learned.lua
-- The learned zone-line graph, shared across every character on this install.
--
-- routing/zonegraph.lua learns a zone line every time the player crosses one, so the travel
-- graph fills itself in from play (docs/ROUTING.md).  Until now that memory lived in the
-- per-character settings file, so a second character started blind and re-walked the same
-- roads the first had already mapped.  A zone line is a fact about the world, not about one
-- character: this module keeps the learned set in one shared file at the install root, merged
-- in for whoever logs in, so the whole account benefits from anyone's exploration.
--
-- It also turns that lived-in graph into something shippable: `L.dump` writes the learned
-- pairs as a paste-ready block for data/zonelines.lua, so a fresh install can start with the
-- roads a real playthrough found rather than only the hand-written seed.
--
-- The file format is deliberately trivial -- a Lua chunk that returns { ["from:to"] = true } --
-- so a corrupt or missing file costs nothing: the edges simply re-learn from play.
--
-- Copyright (c) 2026 Bates LLC.  All rights reserved.

local L = {}

--- Where the shared file lives.  Its own folder, not the per-character settings tree, is the
--- whole point.  Backslashes to match every other path in this addon: it runs under Wine.
function L.path()
    local base = AshitaCore:GetInstallPath():gsub('[\\/]$', '')
    return ('%s\\addons\\Vanaguide\\learned.lua'):format(base)
end

function L.dump_path()
    local base = AshitaCore:GetInstallPath():gsub('[\\/]$', '')
    return ('%s\\addons\\Vanaguide\\graph-dump.lua'):format(base)
end

--- The union of two learned sets.  Keys are "from:to"; both directions are stored by the
--- graph already, so no mirroring is done here.
function L.merge(a, b)
    local out = {}
    for k, v in pairs(a or {}) do if v then out[k] = true end end
    for k, v in pairs(b or {}) do if v then out[k] = true end end
    return out
end

--- The learned set as a Lua source chunk that returns it.  Sorted, so the file is stable
--- across saves and diffs cleanly if it is ever committed.
function L.serialize(tbl)
    local keys = {}
    for k, v in pairs(tbl or {}) do if v then keys[#keys + 1] = k end end
    table.sort(keys)
    local out = {
        '-- Vanaguide :: learned zone lines, shared across every character on this install.',
        '-- Generated by core/learned.lua from play.  Safe to delete; it refills from play.',
        '-- Copyright (c) 2026 Bates LLC.  All rights reserved.',
        'return {',
    }
    for _, k in ipairs(keys) do out[#out + 1] = ("  ['%s'] = true,"):format(k) end
    out[#out + 1] = '}'
    out[#out + 1] = ''
    return table.concat(out, '\n')
end

--- Parse a serialized chunk back to a table.  Guarded: any error yields an empty set rather
--- than taking the addon down, because a half-written or hand-mangled file must not.
function L.parse(str)
    if type(str) ~= 'string' or str == '' then return {} end
    local chunk = loadstring(str)
    if chunk == nil then return {} end
    local okc, t = pcall(chunk)
    if not okc or type(t) ~= 'table' then return {} end
    local out = {}
    for k, v in pairs(t) do
        if v and type(k) == 'string' and k:match('^%d+:%d+$') then out[k] = true end
    end
    return out
end

--- The learned pairs as a sorted, de-duplicated list of { from, to } with from < to -- the
--- shape data/zonelines.lua's Z.walk uses, so a dump can be pasted straight in.
function L.pairs_list(tbl)
    local seen, list = {}, {}
    for k, v in pairs(tbl or {}) do
        if v then
            local a, b = k:match('^(%d+):(%d+)$')
            if a ~= nil then
                a, b = tonumber(a), tonumber(b)
                local lo, hi = math.min(a, b), math.max(a, b)
                local canon = lo .. ':' .. hi
                if not seen[canon] then
                    seen[canon] = true
                    list[#list + 1] = { lo, hi }
                end
            end
        end
    end
    table.sort(list, function (p, q) return p[1] == q[1] and p[2] < q[2] or p[1] < q[1] end)
    return list
end

--- A paste-ready block for data/zonelines.lua, wrapping pairs eight to a line the way the
--- generated file does.  `name` is an optional callback (id -> string) so the comment names
--- the zones; without it the block is still valid, just terser.
function L.dump_block(tbl, name)
    local list = L.pairs_list(tbl)
    local out = {
        '-- Learned zone lines, dumped from play by /vg dump graph.',
        ('-- %d crossing%s.  Paste the pairs into data/zonelines.lua Z.walk (they are already')
            :format(#list, #list == 1 and '' or 's'),
        '-- de-duplicated and ordered); a seeded copy needs no per-character learning.',
        'Z.learned_walk = {',
    }
    local line = '   '
    for i, p in ipairs(list) do
        line = line .. (' { %d, %d },'):format(p[1], p[2])
        if i % 8 == 0 then out[#out + 1] = line; line = '   ' end
    end
    if line ~= '   ' then out[#out + 1] = line end
    out[#out + 1] = '}'
    if name ~= nil then
        out[#out + 1] = ''
        for _, p in ipairs(list) do
            out[#out + 1] = ('-- %d %s  <->  %d %s')
                :format(p[1], name(p[1]) or '?', p[2], name(p[2]) or '?')
        end
    end
    out[#out + 1] = ''
    return table.concat(out, '\n')
end

-- ---- file I/O (thin wrappers; the logic above is what the tests exercise) ---------------

function L.load()
    local fh = io.open(L.path(), 'r')
    if fh == nil then return {} end
    local body = fh:read('*a'); fh:close()
    return L.parse(body)
end

function L.save(tbl)
    local fh = io.open(L.path(), 'w')
    if fh == nil then return false end
    fh:write(L.serialize(tbl)); fh:close()
    return true
end

function L.dump(tbl, name)
    local fh = io.open(L.dump_path(), 'w')
    if fh == nil then return nil end
    fh:write(L.dump_block(tbl, name)); fh:close()
    return L.dump_path()
end

return L
