-- Vanaguide :: data/achievements.lua
-- GENERATED by tools/gen_achievements.py from the RetroAchievements FFXI sets.  Do not hand-edit;
-- correct a mapping in tools/achievement_overrides.json and regenerate.
-- Source: nothing yet - no RetroAchievements web API key has been used to generate this file
--
-- One entry per set, in guide order.  Per achievement: id, title, description, points, type
-- (progression / win_condition / missable, or nil), badge, order (RetroAchievements display
-- order), game_id, and `map` when the description names something the guide knows:
--   kind        quest | mission | job | level | rank | key_item | item | nm | zone
--   area, id    quest or mission key;  job, level;  rank;  ki;  item, count;  name
--   zone, x, z  where to go, when known
--   confidence  0..1; guides/achievements.lua turns it into a completion tag only at >= 0.75
--   method      the rule that matched
--
-- Achievement text is RetroAchievements' own; progress is never stored here (the launcher
-- writes config/addons/Vanaguide/retroachievements.json).  See docs/RETROACHIEVEMENTS.md.
--
-- Copyright (c) 2026 Bates LLC. All rights reserved.

local A = {}

A.complete_at = 0.75

A.sets = {
}

A.by_id = {}
for _, set in ipairs(A.sets) do
    for _, a in ipairs(set.achievements) do A.by_id[a.id] = a end
end

--- One achievement by its RetroAchievements id, or nil.
function A.get(id) return A.by_id[tonumber(id)] end

return A
