-- Vanaguide :: data/zonelines.lua
-- GENERATED by tools/gen_zonelines.py from a LandSandBoat checkout.  Do not
-- hand-edit.
--
-- Every pair of zones the server will walk a player between, from sql/zonelines.sql,
-- and every other way it moves one: ferries and airships from sql/transport.sql, and
-- the maws, waypoints, doors and Home Points its NPC scripts run (tools/lsbtravel.py).
-- Zone ids and the fact that two zones touch are game facts, not authored content.
--
-- data/travel.lua holds the hand-written half -- the airship pass, spells, anything
-- a server script does not say.
--
-- Copyright (c) 2026 Bates LLC.  All rights reserved.

local Z = {}

Z.walk = {
    { 2, 104 }, { 2, 231 }, { 4, 118 }, { 5, 6 }, { 5, 112 }, { 7, 8 }, { 7, 198 }, { 9, 10 },
    { 9, 111 }, { 11, 12 }, { 11, 106 }, { 11, 196 }, { 12, 13 }, { 16, 17 }, { 18, 19 },
    { 20, 21 }, { 22, 23 }, { 24, 25 }, { 24, 26 }, { 25, 26 }, { 25, 28 }, { 26, 27 },
    { 26, 32 }, { 33, 34 }, { 33, 37 }, { 34, 35 }, { 48, 50 }, { 48, 51 }, { 48, 52 },
    { 51, 52 }, { 51, 62 }, { 51, 65 }, { 51, 68 }, { 52, 62 }, { 52, 65 }, { 52, 67 },
    { 52, 68 }, { 52, 72 }, { 53, 79 }, { 54, 57 }, { 54, 79 }, { 57, 79 }, { 61, 62 },
    { 61, 64 }, { 61, 72 }, { 62, 68 }, { 72, 79 }, { 78, 79 }, { 80, 81 }, { 81, 82 },
    { 82, 83 }, { 82, 84 }, { 82, 85 }, { 83, 91 }, { 84, 91 }, { 84, 136 }, { 84, 175 },
    { 87, 88 }, { 88, 89 }, { 89, 90 }, { 90, 91 }, { 90, 92 }, { 91, 98 }, { 91, 171 },
    { 94, 95 }, { 95, 96 }, { 96, 97 }, { 97, 98 }, { 97, 99 }, { 98, 164 }, { 100, 101 },
    { 100, 102 }, { 100, 140 }, { 100, 167 }, { 100, 230 }, { 100, 231 }, { 101, 166 },
    { 101, 190 }, { 101, 230 }, { 102, 103 }, { 102, 104 }, { 102, 193 }, { 103, 108 },
    { 103, 212 }, { 103, 248 }, { 104, 105 }, { 104, 149 }, { 104, 190 }, { 105, 110 },
    { 105, 111 }, { 105, 195 }, { 105, 244 }, { 106, 107 }, { 106, 108 }, { 106, 143 },
    { 106, 191 }, { 106, 236 }, { 107, 191 }, { 107, 234 }, { 107, 235 }, { 108, 109 },
    { 108, 196 }, { 109, 110 }, { 109, 147 }, { 110, 120 }, { 110, 197 }, { 110, 245 },
    { 111, 112 }, { 111, 166 }, { 111, 204 }, { 112, 161 }, { 113, 128 }, { 113, 174 },
    { 113, 201 }, { 113, 212 }, { 114, 125 }, { 114, 173 }, { 114, 208 }, { 114, 209 },
    { 115, 116 }, { 115, 145 }, { 115, 146 }, { 115, 192 }, { 115, 194 }, { 115, 238 },
    { 115, 240 }, { 116, 117 }, { 116, 192 }, { 116, 194 }, { 116, 241 }, { 117, 118 },
    { 117, 119 }, { 117, 198 }, { 118, 198 }, { 118, 213 }, { 118, 249 }, { 119, 120 },
    { 119, 121 }, { 119, 151 }, { 120, 200 }, { 120, 246 }, { 121, 122 }, { 121, 153 },
    { 121, 154 }, { 122, 251 }, { 123, 124 }, { 123, 176 }, { 123, 205 }, { 123, 250 },
    { 124, 159 }, { 124, 160 }, { 124, 205 }, { 125, 173 }, { 125, 174 }, { 125, 208 },
    { 125, 247 }, { 126, 127 }, { 126, 184 }, { 126, 246 }, { 130, 177 }, { 130, 178 },
    { 130, 180 }, { 130, 251 }, { 136, 137 }, { 137, 138 }, { 138, 155 }, { 139, 142 },
    { 140, 141 }, { 140, 142 }, { 141, 142 }, { 143, 144 }, { 145, 146 }, { 147, 148 },
    { 149, 150 }, { 151, 152 }, { 153, 154 }, { 153, 202 }, { 155, 156 }, { 159, 160 },
    { 159, 163 }, { 160, 163 }, { 160, 211 }, { 161, 162 }, { 162, 165 }, { 167, 233 },
    { 168, 208 }, { 169, 170 }, { 169, 192 }, { 169, 239 }, { 172, 173 }, { 172, 234 },
    { 176, 252 }, { 178, 181 }, { 203, 204 }, { 204, 206 }, { 205, 207 }, { 208, 209 },
    { 230, 231 }, { 231, 232 }, { 234, 235 }, { 235, 236 }, { 235, 237 }, { 238, 239 },
    { 238, 240 }, { 239, 241 }, { 240, 241 }, { 243, 244 }, { 244, 245 }, { 245, 246 },
    { 256, 257 }, { 256, 258 }, { 256, 261 }, { 257, 258 }, { 260, 261 }, { 260, 269 },
    { 261, 268 }, { 262, 268 }, { 262, 272 }, { 263, 270 }, { 263, 273 }, { 265, 269 },
    { 265, 273 }, { 266, 272 }, { 266, 273 }, { 267, 273 }, { 267, 281 }, { 268, 270 },
    { 269, 270 }, { 270, 272 }, { 270, 273 },
}

-- Ferries and airships: boarded and waited for, not walked through. Without
-- these the base world and Aht Urhgan share no connection at all -- the Mhaura
-- ferry is the only crossing -- and a third of the quest zones are unreachable.
-- The cost is the seconds a router should treat the trip as; the real wait
-- varies with the ship's schedule and is not knowable from a table.
Z.transit = {
    { from = 236, to = 246, cost = 300, kind = 'transit', via = 'Airship from Port Bastok to Port Jeuno' },
    { from = 246, to = 236, cost = 300, kind = 'transit', via = 'Airship from Port Jeuno to Port Bastok' },
    { from = 246, to = 250, cost = 300, kind = 'transit', via = 'Airship from Port Jeuno to Kazham' },
    { from = 250, to = 246, cost = 300, kind = 'transit', via = 'Airship from Kazham to Port Jeuno' },
    { from = 246, to = 232, cost = 300, kind = 'transit', via = 'Airship from Port Jeuno to Port San dOria' },
    { from = 232, to = 246, cost = 300, kind = 'transit', via = 'Airship from Port San dOria to Port Jeuno' },
    { from = 246, to = 240, cost = 300, kind = 'transit', via = 'Airship from Port Jeuno to Port Windurst' },
    { from = 240, to = 246, cost = 300, kind = 'transit', via = 'Airship from Port Windurst to Port Jeuno' },
    { from = 249, to = 248, cost = 300, kind = 'transit', via = 'Boat from Mhaura to Selbina' },
    { from = 248, to = 249, cost = 300, kind = 'transit', via = 'Boat from Selbina to Mhaura' },
    { from = 249, to = 50, cost = 300, kind = 'transit', via = 'Boat from Mhaura to Aht Urhgan Whitegate' },
    { from = 50, to = 249, cost = 300, kind = 'transit', via = 'Boat from Aht Urhgan Whitegate to Mhaura' },
    { from = 53, to = 50, cost = 300, kind = 'transit', via = 'Boat from Nashmau to Aht Urhgan Whitegate' },
    { from = 50, to = 53, cost = 300, kind = 'transit', via = 'Boat from Aht Urhgan Whitegate to Nashmau' },

    -- Not boats: the NPC events that move a player to another zone -- Cavernous
    -- Maws, waypoints, and the doors and transporters listed in tools/lsbtravel.py.
    -- The comment above each is where the server says so.  Most have a condition,
    -- which the text in brackets tells the player; a table cannot check it.
    -- scripts/zones/Abyssea-Altepa/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1296
    { from = 218, to = 107, cost = 120, kind = 'transit', via = 'Cavernous Maw in Abyssea-Altepa to South Gustaberg' },
    -- scripts/zones/Abyssea-Attohwa/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1295
    { from = 215, to = 118, cost = 120, kind = 'transit', via = 'Cavernous Maw in Abyssea-Attohwa to Buburimu Peninsula' },
    -- scripts/zones/Abyssea-Empyreal_Paradox/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1299
    { from = 255, to = 126, cost = 120, kind = 'transit', via = 'Cavernous Maw in Abyssea-Empyreal Paradox to Qufim Island' },
    -- scripts/zones/Abyssea-Grauberg/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1298
    { from = 254, to = 106, cost = 120, kind = 'transit', via = 'Cavernous Maw in Abyssea-Grauberg to North Gustaberg' },
    -- scripts/zones/Abyssea-Konschtat/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1291
    { from = 15, to = 108, cost = 120, kind = 'transit', via = 'Cavernous Maw in Abyssea-Konschtat to Konschtat Highlands' },
    -- scripts/zones/Abyssea-La_Theine/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1290
    { from = 132, to = 102, cost = 120, kind = 'transit', via = 'Cavernous Maw in Abyssea-La Theine to La Theine Plateau' },
    -- scripts/zones/Abyssea-Misareaux/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1294
    { from = 216, to = 103, cost = 120, kind = 'transit', via = 'Cavernous Maw in Abyssea-Misareaux to Valkurm Dunes' },
    -- scripts/zones/Abyssea-Tahrongi/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1292
    { from = 45, to = 117, cost = 120, kind = 'transit', via = 'Cavernous Maw in Abyssea-Tahrongi to Tahrongi Canyon' },
    -- scripts/zones/Abyssea-Uleguerand/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1297
    { from = 253, to = 112, cost = 120, kind = 'transit', via = 'Cavernous Maw in Abyssea-Uleguerand to Xarcabard' },
    -- scripts/zones/Abyssea-Vunkerl/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1293
    { from = 217, to = 104, cost = 120, kind = 'transit', via = 'Cavernous Maw in Abyssea-Vunkerl to Jugner Forest' },
    -- scripts/zones/Batallia_Downs/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:14
    { from = 105, to = 84, cost = 120, kind = 'transit', via = 'Cavernous Maw in Batallia Downs to Batallia Downs [S] (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/Batallia_Downs_[S]/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:23
    { from = 84, to = 105, cost = 120, kind = 'transit', via = 'Cavernous Maw in Batallia Downs [S] to Batallia Downs (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/Buburimu_Peninsula/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1248
    { from = 118, to = 215, cost = 120, kind = 'transit', via = 'Cavernous Maw in Buburimu Peninsula to Abyssea-Attohwa (Abyssea; level 30 or higher)' },
    -- scripts/zones/East_Ronfaure/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:20
    { from = 101, to = 81, cost = 120, kind = 'transit', via = 'Cavernous Maw in East Ronfaure to East Ronfaure [S] (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/East_Ronfaure_[S]/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:29
    { from = 81, to = 101, cost = 120, kind = 'transit', via = 'Cavernous Maw in East Ronfaure [S] to East Ronfaure (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/Jugner_Forest/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:17
    { from = 104, to = 82, cost = 120, kind = 'transit', via = 'Cavernous Maw in Jugner Forest to Jugner Forest [S] (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/Jugner_Forest/npcs/Cavernous_Maw_2.lua + scripts/globals/abyssea.lua:1246
    { from = 104, to = 217, cost = 120, kind = 'transit', via = 'Cavernous Maw in Jugner Forest to Abyssea-Vunkerl (Abyssea; level 30 or higher)' },
    -- scripts/zones/Jugner_Forest_[S]/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:26
    { from = 82, to = 104, cost = 120, kind = 'transit', via = 'Cavernous Maw in Jugner Forest [S] to Jugner Forest (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/Konschtat_Highlands/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1244
    { from = 108, to = 15, cost = 120, kind = 'transit', via = 'Cavernous Maw in Konschtat Highlands to Abyssea-Konschtat (Abyssea; level 30 or higher)' },
    -- scripts/zones/La_Theine_Plateau/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1243
    { from = 102, to = 132, cost = 120, kind = 'transit', via = 'Cavernous Maw in La Theine Plateau to Abyssea-La Theine (Abyssea; level 30 or higher)' },
    -- scripts/zones/Meriphataud_Mountains/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:19
    { from = 119, to = 97, cost = 120, kind = 'transit', via = 'Cavernous Maw in Meriphataud Mountains to Meriphataud Mountains [S] (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/Meriphataud_Mountains_[S]/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:28
    { from = 97, to = 119, cost = 120, kind = 'transit', via = 'Cavernous Maw in Meriphataud Mountains [S] to Meriphataud Mountains (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/North_Gustaberg/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:21
    { from = 106, to = 88, cost = 120, kind = 'transit', via = 'Cavernous Maw in North Gustaberg to North Gustaberg [S] (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/North_Gustaberg/npcs/Cavernous_Maw_2.lua + scripts/globals/abyssea.lua:1251
    { from = 106, to = 254, cost = 120, kind = 'transit', via = 'Cavernous Maw in North Gustaberg to Abyssea-Grauberg (Abyssea; level 30 or higher)' },
    -- scripts/zones/North_Gustaberg_[S]/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:30
    { from = 88, to = 106, cost = 120, kind = 'transit', via = 'Cavernous Maw in North Gustaberg [S] to North Gustaberg (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/Pashhow_Marshlands/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:18
    { from = 109, to = 90, cost = 120, kind = 'transit', via = 'Cavernous Maw in Pashhow Marshlands to Pashhow Marshlands [S] (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/Pashhow_Marshlands_[S]/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:27
    { from = 90, to = 109, cost = 120, kind = 'transit', via = 'Cavernous Maw in Pashhow Marshlands [S] to Pashhow Marshlands (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/Rolanberry_Fields/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:15
    { from = 110, to = 91, cost = 120, kind = 'transit', via = 'Cavernous Maw in Rolanberry Fields to Rolanberry Fields [S] (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/Rolanberry_Fields_[S]/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:24
    { from = 91, to = 110, cost = 120, kind = 'transit', via = 'Cavernous Maw in Rolanberry Fields [S] to Rolanberry Fields (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/Sauromugue_Champaign/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:16
    { from = 120, to = 98, cost = 120, kind = 'transit', via = 'Cavernous Maw in Sauromugue Champaign to Sauromugue Champaign [S] (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/Sauromugue_Champaign_[S]/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:25
    { from = 98, to = 120, cost = 120, kind = 'transit', via = 'Cavernous Maw in Sauromugue Champaign [S] to Sauromugue Champaign (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/South_Gustaberg/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1249
    { from = 107, to = 218, cost = 120, kind = 'transit', via = 'Cavernous Maw in South Gustaberg to Abyssea-Altepa (Abyssea; level 30 or higher)' },
    -- scripts/zones/Tahrongi_Canyon/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1245
    { from = 117, to = 45, cost = 120, kind = 'transit', via = 'Cavernous Maw in Tahrongi Canyon to Abyssea-Tahrongi (Abyssea; level 30 or higher)' },
    -- scripts/zones/Valkurm_Dunes/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1247
    { from = 103, to = 216, cost = 120, kind = 'transit', via = 'Cavernous Maw in Valkurm Dunes to Abyssea-Misareaux (Abyssea; level 30 or higher)' },
    -- scripts/zones/West_Sarutabaruta/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:22
    { from = 115, to = 95, cost = 120, kind = 'transit', via = 'Cavernous Maw in West Sarutabaruta to West Sarutabaruta [S] (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/West_Sarutabaruta_[S]/npcs/Cavernous_Maw.lua + scripts/globals/maws.lua:31
    { from = 95, to = 115, cost = 120, kind = 'transit', via = 'Cavernous Maw in West Sarutabaruta [S] to West Sarutabaruta (Wings of the Goddess; the maw must be opened first)' },
    -- scripts/zones/Xarcabard/npcs/Cavernous_Maw.lua + scripts/globals/abyssea.lua:1250
    { from = 112, to = 253, cost = 120, kind = 'transit', via = 'Cavernous Maw in Xarcabard to Abyssea-Uleguerand (Abyssea; level 30 or higher)' },
    -- scripts/missions/cop/helpers.lua:19
    { from = 102, to = 14, cost = 1800, time = 120, kind = 'transit', via = 'Shattered Telepoint in La Theine Plateau to Hall of Transference (only during Chains of Promathia 1-2 and 1-3)' },
    -- scripts/missions/cop/helpers.lua:20
    { from = 108, to = 14, cost = 1800, time = 120, kind = 'transit', via = 'Shattered Telepoint in Konschtat Highlands to Hall of Transference (only during Chains of Promathia 1-2 and 1-3)' },
    -- scripts/missions/cop/helpers.lua:21
    { from = 117, to = 14, cost = 1800, time = 120, kind = 'transit', via = 'Shattered Telepoint in Tahrongi Canyon to Hall of Transference (only during Chains of Promathia 1-2 and 1-3)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 245, to = 256, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Lower Jeuno to Western Adoulin (the Adoulin waypoint must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 245, to = 257, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Lower Jeuno to Eastern Adoulin (the Adoulin waypoint must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 256, to = 257, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Western Adoulin to Eastern Adoulin (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 256, to = 261, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Western Adoulin to Ceizak Battlegrounds (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 256, to = 260, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Western Adoulin to Yahse Hunting Grounds (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 256, to = 262, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Western Adoulin to Foret de Hennetiel (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 256, to = 265, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Western Adoulin to Morimar Basalt Fields (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 256, to = 263, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Western Adoulin to Yorcia Weald (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 256, to = 266, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Western Adoulin to Marjami Ravine (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 256, to = 267, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Western Adoulin to Kamihr Drifts (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 256, to = 245, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Western Adoulin to Lower Jeuno (kinetic units)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 256, to = 258, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Western Adoulin to Rala Waterways (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 256, to = 270, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Western Adoulin to Cirdas Caverns (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 256, to = 274, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Western Adoulin to Outer Ra\'Kaznar (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 257, to = 256, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Eastern Adoulin to Western Adoulin (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 257, to = 261, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Eastern Adoulin to Ceizak Battlegrounds (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 257, to = 260, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Eastern Adoulin to Yahse Hunting Grounds (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 257, to = 262, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Eastern Adoulin to Foret de Hennetiel (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 257, to = 265, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Eastern Adoulin to Morimar Basalt Fields (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 257, to = 263, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Eastern Adoulin to Yorcia Weald (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 257, to = 266, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Eastern Adoulin to Marjami Ravine (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 257, to = 267, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Eastern Adoulin to Kamihr Drifts (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 257, to = 245, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Eastern Adoulin to Lower Jeuno (kinetic units)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 257, to = 258, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Eastern Adoulin to Rala Waterways (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 257, to = 270, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Eastern Adoulin to Cirdas Caverns (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 257, to = 274, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Eastern Adoulin to Outer Ra\'Kaznar (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 260, to = 256, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Yahse Hunting Grounds to Western Adoulin (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 260, to = 257, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Yahse Hunting Grounds to Eastern Adoulin (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 260, to = 245, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Yahse Hunting Grounds to Lower Jeuno (kinetic units)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 260, to = 258, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Yahse Hunting Grounds to Rala Waterways (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 260, to = 263, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Yahse Hunting Grounds to Yorcia Weald (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 260, to = 270, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Yahse Hunting Grounds to Cirdas Caverns (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 260, to = 274, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Yahse Hunting Grounds to Outer Ra\'Kaznar (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 261, to = 256, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Ceizak Battlegrounds to Western Adoulin (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 261, to = 257, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Ceizak Battlegrounds to Eastern Adoulin (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 261, to = 245, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Ceizak Battlegrounds to Lower Jeuno (kinetic units)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 261, to = 258, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Ceizak Battlegrounds to Rala Waterways (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 261, to = 263, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Ceizak Battlegrounds to Yorcia Weald (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 261, to = 270, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Ceizak Battlegrounds to Cirdas Caverns (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 261, to = 274, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Ceizak Battlegrounds to Outer Ra\'Kaznar (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 262, to = 256, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Foret de Hennetiel to Western Adoulin (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 262, to = 257, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Foret de Hennetiel to Eastern Adoulin (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 262, to = 245, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Foret de Hennetiel to Lower Jeuno (kinetic units)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 262, to = 258, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Foret de Hennetiel to Rala Waterways (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 262, to = 263, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Foret de Hennetiel to Yorcia Weald (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 262, to = 270, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Foret de Hennetiel to Cirdas Caverns (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 262, to = 274, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Foret de Hennetiel to Outer Ra\'Kaznar (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 263, to = 256, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Yorcia Weald to Western Adoulin (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 263, to = 257, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Yorcia Weald to Eastern Adoulin (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 263, to = 245, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Yorcia Weald to Lower Jeuno (kinetic units)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 263, to = 258, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Yorcia Weald to Rala Waterways (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 263, to = 270, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Yorcia Weald to Cirdas Caverns (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 263, to = 274, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Yorcia Weald to Outer Ra\'Kaznar (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 265, to = 256, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Morimar Basalt Fields to Western Adoulin (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 265, to = 257, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Morimar Basalt Fields to Eastern Adoulin (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 265, to = 245, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Morimar Basalt Fields to Lower Jeuno (kinetic units)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 265, to = 258, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Morimar Basalt Fields to Rala Waterways (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 265, to = 263, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Morimar Basalt Fields to Yorcia Weald (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 265, to = 270, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Morimar Basalt Fields to Cirdas Caverns (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 265, to = 274, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Morimar Basalt Fields to Outer Ra\'Kaznar (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 266, to = 256, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Marjami Ravine to Western Adoulin (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 266, to = 257, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Marjami Ravine to Eastern Adoulin (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 266, to = 245, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Marjami Ravine to Lower Jeuno (kinetic units)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 266, to = 258, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Marjami Ravine to Rala Waterways (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 266, to = 263, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Marjami Ravine to Yorcia Weald (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 266, to = 270, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Marjami Ravine to Cirdas Caverns (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 266, to = 274, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Marjami Ravine to Outer Ra\'Kaznar (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 267, to = 256, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Kamihr Drifts to Western Adoulin (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 267, to = 257, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Kamihr Drifts to Eastern Adoulin (kinetic units; the waypoint there must be attuned)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 267, to = 245, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Kamihr Drifts to Lower Jeuno (kinetic units)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 267, to = 258, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Kamihr Drifts to Rala Waterways (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 267, to = 263, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Kamihr Drifts to Yorcia Weald (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 267, to = 270, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Kamihr Drifts to Cirdas Caverns (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/globals/waypoint.lua:26,403,408 (destinations, then the two rules)
    { from = 267, to = 274, cost = 120, kind = 'transit', net = 'waypoint', via = 'Waypoint in Kamihr Drifts to Outer Ra\'Kaznar (kinetic units; the Enigmatic Device must be unlocked)' },
    -- scripts/zones/Hall_of_Transference/npcs/_0e0.lua:20
    { from = 14, to = 16, cost = 120, kind = 'transit', via = 'Cermet Gate in Hall of Transference to Promyvion-Holla (Chains of Promathia 1-2 or later)' },
    -- scripts/zones/Hall_of_Transference/npcs/_0e1.lua:20
    { from = 14, to = 18, cost = 120, kind = 'transit', via = 'Cermet Gate in Hall of Transference to Promyvion-Dem (Chains of Promathia 1-2 or later)' },
    -- scripts/zones/Hall_of_Transference/npcs/_0e2.lua:20
    { from = 14, to = 20, cost = 120, kind = 'transit', via = 'Cermet Gate in Hall of Transference to Promyvion-Mea (Chains of Promathia 1-2 or later)' },
    -- scripts/zones/Spire_of_Holla/npcs/Radiant_Aureole.lua:14
    { from = 17, to = 102, cost = 120, kind = 'transit', via = 'Radiant Aureole in Spire of Holla to La Theine Plateau' },
    -- scripts/zones/Spire_of_Dem/npcs/Radiant_Aureole.lua:15
    { from = 19, to = 108, cost = 120, kind = 'transit', via = 'Radiant Aureole in Spire of Dem to Konschtat Highlands' },
    -- scripts/zones/Spire_of_Mea/npcs/Radiant_Aureole.lua:14
    { from = 21, to = 117, cost = 120, kind = 'transit', via = 'Radiant Aureole in Spire of Mea to Tahrongi Canyon' },
    -- scripts/zones/Spire_of_Vahzl/npcs/Radiant_Aureole.lua:14
    { from = 23, to = 9, cost = 120, kind = 'transit', via = 'Radiant Aureole in Spire of Vahzl to Pso\'Xja' },
    -- scripts/zones/La_Theine_Plateau/npcs/Dimensional_Portal.lua:20
    { from = 102, to = 33, cost = 1800, time = 120, kind = 'transit', via = 'Dimensional Portal in La Theine Plateau to Al\'Taieu (after Chains of Promathia 7-5)' },
    -- scripts/zones/Konschtat_Highlands/npcs/Dimensional_Portal.lua:21
    { from = 108, to = 33, cost = 1800, time = 120, kind = 'transit', via = 'Dimensional Portal in Konschtat Highlands to Al\'Taieu (after Chains of Promathia 7-5)' },
    -- scripts/zones/Tahrongi_Canyon/npcs/Dimensional_Portal.lua:21
    { from = 117, to = 33, cost = 1800, time = 120, kind = 'transit', via = 'Dimensional Portal in Tahrongi Canyon to Al\'Taieu (after Chains of Promathia 7-5)' },
    -- scripts/zones/AlTaieu/npcs/Dimensional_Portal.lua:19
    { from = 33, to = 102, cost = 120, kind = 'transit', via = 'Dimensional Portal in Al\'Taieu to La Theine Plateau' },
    -- scripts/zones/AlTaieu/npcs/Dimensional_Portal.lua:21
    { from = 33, to = 108, cost = 120, kind = 'transit', via = 'Dimensional Portal in Al\'Taieu to Konschtat Highlands' },
    -- scripts/zones/AlTaieu/npcs/Dimensional_Portal.lua:23
    { from = 33, to = 117, cost = 120, kind = 'transit', via = 'Dimensional Portal in Al\'Taieu to Tahrongi Canyon' },
    -- scripts/zones/Grand_Palace_of_HuXzoi/npcs/_iya.lua:15
    { from = 34, to = 35, cost = 120, kind = 'transit', via = 'Gate of the Gods in Grand Palace of Hu\'Xzoi to The Garden of Ru\'Hmet' },
    -- scripts/zones/The_Garden_of_RuHmet/npcs/_0zs.lua:19
    { from = 35, to = 34, cost = 120, kind = 'transit', via = 'Particle Gate in The Garden of Ru\'Hmet to Grand Palace of Hu\'Xzoi (after Chains of Promathia 8-3)' },
    -- scripts/zones/Lower_Delkfutts_Tower/npcs/Cermet_Door.lua:16
    { from = 184, to = 158, cost = 120, kind = 'transit', via = 'Cermet Door in Lower Delkfutts Tower to Upper Delkfutts Tower' },
    -- scripts/zones/Upper_Delkfutts_Tower/npcs/_4e1.lua:15
    { from = 158, to = 184, cost = 120, kind = 'transit', via = 'Cermet Door in Upper Delkfutts Tower to Lower Delkfutts Tower' },
    -- scripts/zones/Qufim_Island/npcs/Transcendental_Radiance.lua:57
    { from = 126, to = 255, cost = 120, kind = 'transit', via = 'Transcendental Radiance in Qufim Island to Abyssea-Empyreal Paradox (Abyssea: Beneath a Blood Red Sky, and a Traverser Stone)' },
    -- scripts/zones/Eastern_Adoulin/npcs/Eppel-Treppel.lua:16
    { from = 257, to = 284, cost = 120, kind = 'transit', via = 'Eppel-Treppel in Eastern Adoulin to Celennia Memorial Library' },
    -- scripts/zones/Celennia_Memorial_Library/npcs/Door_Back_to_Town.lua:15
    { from = 284, to = 257, cost = 120, kind = 'transit', via = 'Door: Back to Town in Celennia Memorial Library to Eastern Adoulin' },
    -- scripts/zones/Kamihr_Drifts/npcs/Liseran_Door_Entrance.lua:16
    { from = 267, to = 274, cost = 120, kind = 'transit', via = 'Liseran Door: Entrance in Kamihr Drifts to Outer Ra\'Kaznar' },
    -- scripts/zones/Outer_RaKaznar/npcs/Liseran_Door_Exit.lua:16
    { from = 274, to = 267, cost = 120, kind = 'transit', via = 'Liseran Door: Exit in Outer Ra\'Kaznar to Kamihr Drifts' },
    -- scripts/zones/Outer_RaKaznar/npcs/Vertical_Transit_Device_7.lua:15
    { from = 274, to = 276, cost = 120, kind = 'transit', via = 'Vertical Transit Device in Outer Ra\'Kaznar to Ra\'Kaznar Inner Court' },
    -- scripts/zones/RaKaznar_Inner_Court/npcs/Vertical_Transit_Device_1.lua:15
    { from = 276, to = 277, cost = 120, kind = 'transit', via = 'Vertical Transit Device in Ra\'Kaznar Inner Court to Ra\'Kaznar Turris' },
    -- scripts/zones/RaKaznar_Inner_Court/npcs/Vertical_Transit_Device_2.lua:15
    { from = 276, to = 274, cost = 120, kind = 'transit', via = 'Vertical Transit Device in Ra\'Kaznar Inner Court to Outer Ra\'Kaznar' },
    -- scripts/zones/RaKaznar_Turris/Zone.lua:63
    { from = 277, to = 276, cost = 120, kind = 'transit', via = 'Entrance in Ra\'Kaznar Turris to Ra\'Kaznar Inner Court' },
}

-- Home Points: any one warps to any other the player has touched (for gil), so they
-- are a network, not a list of pairs -- routing/zonegraph.lua joins them through one
-- hub.  Priced as a last resort (`cost`): they are the only way back to Tavnazia, and
-- no table can say which ones this character has touched.  `time` is the warp itself.
-- scripts/globals/homepoint.lua (goToHP) + settings/default/main.lua:329
Z.network = {
    homepoint = {
        cost = 1800,
        time = 120,
        via = {
            [5] = 'Home Point warp to Uleguerand Range (you must have touched a Home Point there)',
            [7] = 'Home Point warp to Attohwa Chasm (you must have touched a Home Point there)',
            [9] = 'Home Point warp to Pso\'Xja (you must have touched a Home Point there)',
            [12] = 'Home Point warp to Newton Movalpolos (you must have touched a Home Point there)',
            [25] = 'Home Point warp to Misareaux Coast (you must have touched a Home Point there)',
            [26] = 'Home Point warp to Tavnazian Safehold (you must have touched a Home Point there)',
            [29] = 'Home Point warp to Riverne-Site B01 (you must have touched a Home Point there)',
            [30] = 'Home Point warp to Riverne-Site A01 (you must have touched a Home Point there)',
            [33] = 'Home Point warp to Al\'Taieu (you must have touched a Home Point there)',
            [34] = 'Home Point warp to Grand Palace of Hu\'Xzoi (you must have touched a Home Point there)',
            [35] = 'Home Point warp to The Garden of Ru\'Hmet (you must have touched a Home Point there)',
            [50] = 'Home Point warp to Aht Urhgan Whitegate (you must have touched a Home Point there)',
            [52] = 'Home Point warp to Bhaflau Thickets (you must have touched a Home Point there)',
            [53] = 'Home Point warp to Nashmau (you must have touched a Home Point there)',
            [61] = 'Home Point warp to Mount Zhayolm (you must have touched a Home Point there)',
            [79] = 'Home Point warp to Caedarva Mire (you must have touched a Home Point there)',
            [80] = 'Home Point warp to Southern San d\'Oria [S] (you must have touched a Home Point there)',
            [87] = 'Home Point warp to Bastok Markets [S] (you must have touched a Home Point there)',
            [94] = 'Home Point warp to Windurst Waters [S] (you must have touched a Home Point there)',
            [113] = 'Home Point warp to Cape Teriggan (you must have touched a Home Point there)',
            [126] = 'Home Point warp to Qufim Island (you must have touched a Home Point there)',
            [130] = 'Home Point warp to Ru\'Aun Gardens (you must have touched a Home Point there)',
            [137] = 'Home Point warp to Xarcabard [S] (you must have touched a Home Point there)',
            [142] = 'Home Point warp to Yughott Grotto (you must have touched a Home Point there)',
            [143] = 'Home Point warp to Palborough Mines (you must have touched a Home Point there)',
            [145] = 'Home Point warp to Giddeus (you must have touched a Home Point there)',
            [153] = 'Home Point warp to The Boyahda Tree (you must have touched a Home Point there)',
            [155] = 'Home Point warp to Castle Zvahl Keep [S] (you must have touched a Home Point there)',
            [158] = 'Home Point warp to Upper Delkfutts Tower (you must have touched a Home Point there)',
            [160] = 'Home Point warp to Den of Rancor (you must have touched a Home Point there)',
            [162] = 'Home Point warp to Castle Zvahl Keep (you must have touched a Home Point there)',
            [169] = 'Home Point warp to Toraimarai Canal (you must have touched a Home Point there)',
            [178] = 'Home Point warp to The Shrine of Ru\'Avitau (you must have touched a Home Point there)',
            [204] = 'Home Point warp to Fei\'Yin (you must have touched a Home Point there)',
            [205] = 'Home Point warp to Ifrits Cauldron (you must have touched a Home Point there)',
            [208] = 'Home Point warp to Quicksand Caves (you must have touched a Home Point there)',
            [230] = 'Home Point warp to Southern San d\'Oria (you must have touched a Home Point there)',
            [231] = 'Home Point warp to Northern San d\'Oria (you must have touched a Home Point there)',
            [232] = 'Home Point warp to Port San d\'Oria (you must have touched a Home Point there)',
            [234] = 'Home Point warp to Bastok Mines (you must have touched a Home Point there)',
            [235] = 'Home Point warp to Bastok Markets (you must have touched a Home Point there)',
            [236] = 'Home Point warp to Port Bastok (you must have touched a Home Point there)',
            [237] = 'Home Point warp to Metalworks (you must have touched a Home Point there)',
            [238] = 'Home Point warp to Windurst Waters (you must have touched a Home Point there)',
            [239] = 'Home Point warp to Windurst Walls (you must have touched a Home Point there)',
            [240] = 'Home Point warp to Port Windurst (you must have touched a Home Point there)',
            [241] = 'Home Point warp to Windurst Woods (you must have touched a Home Point there)',
            [243] = 'Home Point warp to Ru\'Lude Gardens (you must have touched a Home Point there)',
            [244] = 'Home Point warp to Upper Jeuno (you must have touched a Home Point there)',
            [245] = 'Home Point warp to Lower Jeuno (you must have touched a Home Point there)',
            [246] = 'Home Point warp to Port Jeuno (you must have touched a Home Point there)',
            [247] = 'Home Point warp to Rabao (you must have touched a Home Point there)',
            [248] = 'Home Point warp to Selbina (you must have touched a Home Point there)',
            [249] = 'Home Point warp to Mhaura (you must have touched a Home Point there)',
            [250] = 'Home Point warp to Kazham (you must have touched a Home Point there)',
            [252] = 'Home Point warp to Norg (you must have touched a Home Point there)',
            [256] = 'Home Point warp to Western Adoulin (you must have touched a Home Point there)',
            [257] = 'Home Point warp to Eastern Adoulin (you must have touched a Home Point there)',
            [261] = 'Home Point warp to Ceizak Battlegrounds (you must have touched a Home Point there)',
            [262] = 'Home Point warp to Foret de Hennetiel (you must have touched a Home Point there)',
            [263] = 'Home Point warp to Yorcia Weald (you must have touched a Home Point there)',
            [265] = 'Home Point warp to Morimar Basalt Fields (you must have touched a Home Point there)',
            [266] = 'Home Point warp to Marjami Ravine (you must have touched a Home Point there)',
            [267] = 'Home Point warp to Kamihr Drifts (you must have touched a Home Point there)',
            [276] = 'Home Point warp to Ra\'Kaznar Inner Court (you must have touched a Home Point there)',
            [281] = 'Home Point warp to Leafallia (you must have touched a Home Point there)',
        },
    },
}

return Z
