-- Vanaguide :: data/zonelines.lua
-- GENERATED by tools/gen_zonelines.py from a LandSandBoat checkout.  Do not
-- hand-edit.
--
-- Every pair of zones the server will walk a player between, from sql/zonelines.sql.
-- Zone ids and the fact that two zones touch are game facts, not authored content.
--
-- data/travel.lua holds the other half -- airships, ferries, teleports -- which is
-- hand-written because it carries what to TELL the player, and a table of zone
-- lines cannot say "take the airship to Jeuno".
--
-- Copyright (c) 2026 Bates LLC.  All rights reserved.

local Z = {}

Z.walk = {
    { 2, 104 }, { 2, 231 }, { 4, 118 }, { 5, 6 }, { 5, 112 }, { 7, 8 }, { 7, 198 }, { 9, 10 },
    { 9, 111 }, { 11, 12 }, { 11, 106 }, { 11, 196 }, { 12, 13 }, { 16, 17 }, { 18, 19 },
    { 20, 21 }, { 22, 23 }, { 24, 25 }, { 24, 26 }, { 25, 26 }, { 25, 28 }, { 26, 27 },
    { 26, 32 }, { 33, 34 }, { 33, 37 }, { 34, 35 }, { 48, 50 }, { 48, 51 }, { 48, 52 },
    { 51, 52 }, { 51, 62 }, { 51, 65 }, { 51, 68 }, { 52, 62 }, { 52, 65 }, { 52, 67 },
    { 52, 68 }, { 52, 72 }, { 53, 79 }, { 54, 57 }, { 54, 79 }, { 57, 79 }, { 61, 62 },
    { 61, 64 }, { 61, 72 }, { 62, 68 }, { 72, 79 }, { 78, 79 }, { 80, 81 }, { 81, 82 },
    { 82, 83 }, { 82, 84 }, { 82, 85 }, { 83, 91 }, { 84, 91 }, { 84, 136 }, { 84, 175 },
    { 87, 88 }, { 88, 89 }, { 89, 90 }, { 90, 91 }, { 90, 92 }, { 91, 98 }, { 91, 171 },
    { 94, 95 }, { 95, 96 }, { 96, 97 }, { 97, 98 }, { 97, 99 }, { 98, 164 }, { 100, 101 },
    { 100, 102 }, { 100, 140 }, { 100, 167 }, { 100, 230 }, { 100, 231 }, { 101, 166 },
    { 101, 190 }, { 101, 230 }, { 102, 103 }, { 102, 104 }, { 102, 193 }, { 103, 108 },
    { 103, 212 }, { 103, 248 }, { 104, 105 }, { 104, 149 }, { 104, 190 }, { 105, 110 },
    { 105, 111 }, { 105, 195 }, { 105, 244 }, { 106, 107 }, { 106, 108 }, { 106, 143 },
    { 106, 191 }, { 106, 236 }, { 107, 191 }, { 107, 234 }, { 107, 235 }, { 108, 109 },
    { 108, 196 }, { 109, 110 }, { 109, 147 }, { 110, 120 }, { 110, 197 }, { 110, 245 },
    { 111, 112 }, { 111, 166 }, { 111, 204 }, { 112, 161 }, { 113, 128 }, { 113, 174 },
    { 113, 201 }, { 113, 212 }, { 114, 125 }, { 114, 173 }, { 114, 208 }, { 114, 209 },
    { 115, 116 }, { 115, 145 }, { 115, 146 }, { 115, 192 }, { 115, 194 }, { 115, 238 },
    { 115, 240 }, { 116, 117 }, { 116, 192 }, { 116, 194 }, { 116, 241 }, { 117, 118 },
    { 117, 119 }, { 117, 198 }, { 118, 198 }, { 118, 213 }, { 118, 249 }, { 119, 120 },
    { 119, 121 }, { 119, 151 }, { 120, 200 }, { 120, 246 }, { 121, 122 }, { 121, 153 },
    { 121, 154 }, { 122, 251 }, { 123, 124 }, { 123, 176 }, { 123, 205 }, { 123, 250 },
    { 124, 159 }, { 124, 160 }, { 124, 205 }, { 125, 173 }, { 125, 174 }, { 125, 208 },
    { 125, 247 }, { 126, 127 }, { 126, 184 }, { 126, 246 }, { 130, 177 }, { 130, 178 },
    { 130, 180 }, { 130, 251 }, { 136, 137 }, { 137, 138 }, { 138, 155 }, { 139, 142 },
    { 140, 141 }, { 140, 142 }, { 141, 142 }, { 143, 144 }, { 145, 146 }, { 147, 148 },
    { 149, 150 }, { 151, 152 }, { 153, 154 }, { 153, 202 }, { 155, 156 }, { 159, 160 },
    { 159, 163 }, { 160, 163 }, { 160, 211 }, { 161, 162 }, { 162, 165 }, { 167, 233 },
    { 168, 208 }, { 169, 170 }, { 169, 192 }, { 169, 239 }, { 172, 173 }, { 172, 234 },
    { 176, 252 }, { 178, 181 }, { 203, 204 }, { 204, 206 }, { 205, 207 }, { 208, 209 },
    { 230, 231 }, { 231, 232 }, { 234, 235 }, { 235, 236 }, { 235, 237 }, { 238, 239 },
    { 238, 240 }, { 239, 241 }, { 240, 241 }, { 243, 244 }, { 244, 245 }, { 245, 246 },
    { 256, 257 }, { 256, 258 }, { 256, 261 }, { 257, 258 }, { 260, 261 }, { 260, 269 },
    { 261, 268 }, { 262, 268 }, { 262, 272 }, { 263, 270 }, { 263, 273 }, { 265, 269 },
    { 265, 273 }, { 266, 272 }, { 266, 273 }, { 267, 273 }, { 267, 281 }, { 268, 270 },
    { 269, 270 }, { 270, 272 }, { 270, 273 },
}

-- Ferries and airships: boarded and waited for, not walked through. Without
-- these the base world and Aht Urhgan share no connection at all -- the Mhaura
-- ferry is the only crossing -- and a third of the quest zones are unreachable.
-- The cost is the seconds a router should treat the trip as; the real wait
-- varies with the ship's schedule and is not knowable from a table.
Z.transit = {
    { from = 236, to = 246, cost = 300, kind = 'transit', via = 'Airship from Port Bastok to Port Jeuno' },
    { from = 246, to = 236, cost = 300, kind = 'transit', via = 'Airship from Port Jeuno to Port Bastok' },
    { from = 246, to = 250, cost = 300, kind = 'transit', via = 'Airship from Port Jeuno to Kazham' },
    { from = 250, to = 246, cost = 300, kind = 'transit', via = 'Airship from Kazham to Port Jeuno' },
    { from = 246, to = 232, cost = 300, kind = 'transit', via = 'Airship from Port Jeuno to Port San dOria' },
    { from = 232, to = 246, cost = 300, kind = 'transit', via = 'Airship from Port San dOria to Port Jeuno' },
    { from = 246, to = 240, cost = 300, kind = 'transit', via = 'Airship from Port Jeuno to Port Windurst' },
    { from = 240, to = 246, cost = 300, kind = 'transit', via = 'Airship from Port Windurst to Port Jeuno' },
    { from = 249, to = 248, cost = 300, kind = 'transit', via = 'Boat from Mhaura to Selbina' },
    { from = 248, to = 249, cost = 300, kind = 'transit', via = 'Boat from Selbina to Mhaura' },
    { from = 249, to = 50, cost = 300, kind = 'transit', via = 'Boat from Mhaura to Aht Urhgan Whitegate' },
    { from = 50, to = 249, cost = 300, kind = 'transit', via = 'Boat from Aht Urhgan Whitegate to Mhaura' },
    { from = 53, to = 50, cost = 300, kind = 'transit', via = 'Boat from Nashmau to Aht Urhgan Whitegate' },
    { from = 50, to = 53, cost = 300, kind = 'transit', via = 'Boat from Aht Urhgan Whitegate to Nashmau' },
}

return Z
