#!/usr/bin/env python3
"""Vanaguide :: tools/gen_missions.py

Build the mission database from LandSandBoat's server scripts — the same argument as
tools/gen_quests.py (see docs/QUEST_DATABASE.md), applied to scripts/missions/.

Mission ids matter more than quest ids, because missions are linear: a step waits on
"the current mission number is past this one", so an id that is off by one waits forever
or completes early.  Reading them out of the server's own enum is the only way to be sure.

    tools/gen_missions.py <path to a LandSandBoat checkout> [-o Vanaguide/data/missions.lua]

Copyright (c) 2026 Bates LLC.  All rights reserved.
"""
import argparse
import os
import re
import sys
from collections import defaultdict

# LandSandBoat's log names -> the names core/story.lua uses for packet 0x056 areas.
AREA_LOG = {
    'sandoria': 'sandoria', 'bastok': 'bastok', 'windurst': 'windurst',
    'zilart': 'zilart', 'cop': 'cop', 'toau': 'toau', 'wotg': 'wotg',
    'acp': 'acp', 'amk': 'amk', 'asa': 'asa', 'soa': 'adoulin', 'rov': 'rov',
    'tvr': 'tvr', 'assault': 'assault', 'campaign': 'campaign',
}


def parse_ids(root):
    """scripts/globals/missions.lua -> {area: {CONST: id}}"""
    text = open(os.path.join(root, 'scripts/globals/missions.lua'), encoding='utf-8').read()
    out, area = defaultdict(dict), None
    for line in text.splitlines():
        m = re.search(r"\[xi\.mission\.area\[xi\.mission\.log_id\.(\w+)\]\]", line)
        if m:
            area = m.group(1).lower()
            continue
        m = re.search(r"\['(\w+)'\]\s*=$", line)
        if m:
            area = m.group(1).lower()
            continue
        m = re.match(r"\s*([A-Z][A-Z0-9_]+)\s*=\s*(\d+)", line)
        if m and area:
            out[area][m.group(1)] = int(m.group(2))
    return out


def parse_mission(path, ids):
    text = open(path, encoding='utf-8', errors='replace').read()
    m = re.search(r"Mission:new\(\s*xi\.mission\.log_id\.(\w+)\s*,\s*xi\.mission\.id\.(\w+)\.([A-Z0-9_]+)", text)
    if not m:
        return None
    log_area, id_area, const = m.groups()
    area = AREA_LOG.get(id_area.lower(), id_area.lower())
    mid = ids.get(id_area.lower(), {}).get(const)
    if mid is None:
        mid = ids.get('nation', {}).get(const)
    if mid is None:
        return None

    lines = text.splitlines()
    title = lines[1].lstrip('- ').strip() if len(lines) > 1 else const.title()
    label = None
    if len(lines) > 2:
        # "-- San d'Oria M1-1" on the line under the title, where the file has one.
        m2 = re.match(r"--\s*(.*M\d+-\d+.*)$", lines[2].strip())
        if m2:
            label = m2.group(1).strip()

    npc = None
    for line in lines[:40]:
        m2 = re.match(r"--\s*(.+?)\s*:\s*!pos\s+(-?[\d.]+)\s+(-?[\d.]+)\s+(-?[\d.]+)\s+(\d+)", line)
        if m2:
            npc = {'name': m2.group(1).strip(), 'x': float(m2.group(2)),
                   'y': float(m2.group(3)), 'z': float(m2.group(4)), 'zone': int(m2.group(5))}
            break

    return {'area': area, 'id': mid, 'name': title, 'label': label, 'npc': npc}


def lua_str(s):
    return "'" + str(s).replace('\\', '\\\\').replace("'", "\\'") + "'"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('root')
    ap.add_argument('-o', '--out', default='Vanaguide/data/missions.lua')
    args = ap.parse_args()

    ids = parse_ids(args.root)
    missions, skipped = defaultdict(dict), 0
    for dirpath, _, files in os.walk(os.path.join(args.root, 'scripts/missions')):
        for f in sorted(files):
            if not f.endswith('.lua'):
                continue
            m = parse_mission(os.path.join(dirpath, f), ids)
            if m is None:
                skipped += 1
                continue
            # A mission implemented in several files (first visit / repeat) keeps the entry
            # that carries coordinates.
            have = missions[m['area']].get(m['id'])
            if have is None or (have.get('npc') is None and m['npc'] is not None):
                missions[m['area']][m['id']] = m

    total = sum(len(v) for v in missions.values())
    positioned = sum(1 for a in missions.values() for m in a.values() if m['npc'])

    with open(args.out, 'w', encoding='utf-8') as fh:
        fh.write("""-- Vanaguide :: data/missions.lua
-- GENERATED by tools/gen_missions.py from a LandSandBoat checkout.  Do not hand-edit.
--
-- Mission ids keyed the way packet 0x056 keys them, so `M|area,id|` in a guide and this
-- table are the same numbers.  Missions are linear: `M` waits for the current mission
-- number to pass the id, which is why these are generated rather than remembered.
--
-- Copyright (c) 2026 Bates LLC.  All rights reserved.

local M = {}

""")
        fh.write('M.missions = {\n')
        for area in sorted(missions):
            fh.write('    %s = {\n' % area)
            for mid in sorted(missions[area]):
                m = missions[area][mid]
                bits = ['name = %s' % lua_str(m['name'])]
                if m['label']:
                    bits.append('label = %s' % lua_str(m['label']))
                if m['npc']:
                    n = m['npc']
                    bits += ['zone = %d' % n['zone'], 'x = %.1f' % n['x'],
                             'z = %.1f' % n['z'], 'y = %.1f' % n['y'],
                             'npc = %s' % lua_str(n['name'])]
                fh.write('        [%d] = { %s },\n' % (mid, ', '.join(bits)))
            fh.write('    },\n')
        fh.write('}\n\n')
        fh.write("""function M.get(area, id)
    local a = M.missions[area]
    return a ~= nil and a[id] or nil
end

function M.area(area)
    local out = {}
    for id, m in pairs(M.missions[area] or {}) do out[#out + 1] = { id = id, mission = m } end
    table.sort(out, function(a, b) return a.id < b.id end)
    return out
end

return M
""")

    print('%d missions in %d storylines (%d with coordinates); %d files skipped'
          % (total, len(missions), positioned, skipped))


if __name__ == '__main__':
    sys.exit(main())
