import re, io, datetime
src = open('zs.sql', encoding='utf-8').read()
rows = re.findall(r"INSERT INTO `zone_settings` VALUES \((\d+),'[^']*',\d+,'([^']*)'\)", src)
out = io.StringIO()
out.write("""-- Vanaguide :: data/zone_names.lua
-- Zone id -> canonical name.  GENERATED by tools/gen_zones.py from LandSandBoat's
-- sql/zone_settings.sql (zone ids and names are game facts, not authored content).
-- Do not hand-edit; regenerate.  At runtime the client's own localised zone string
-- (resources 'zones.names') wins; this table is the offline/fallback name and the
-- key the guide files and the zone graph are written against.
local Z = {}
Z.name = {
""")
for zid, name in rows:
    pretty = name.replace('_', ' ')
    # San_dOria -> San d'Oria, ZiTah -> Zi'Tah: the SQL drops the apostrophe and
    # capitalises what followed it, so a lower->upper boundary restores it.
    pretty = re.sub(r'([a-z])([A-Z])', r"\1'\2", pretty)
    out.write("    [%s] = '%s',\n" % (zid, pretty.replace("'", "\\'")))
out.write("""}

Z.id = {}
for id, n in pairs(Z.name) do Z.id[n:lower()] = id end

--- Look up a zone id from a name, case- and underscore-insensitively.
function Z.find(n)
    if type(n) == 'number' then return n end
    if type(n) ~= 'string' then return nil end
    return Z.id[n:lower():gsub('_', ' ')]
end

return Z
""")
open('zone_names.lua','w').write(out.getvalue())
print(len(rows), 'zones')
