#!/usr/bin/env python3
"""Vanaguide :: tools/verify_report.py

Turn verify.csv into something a person can act on.

A raw sweep is a few hundred ok/MISS rows, and the misses are not equal: a marker quest whose
"NPC" is a door, an NPC LandSandBoat never spawns, and a genuinely wrong coordinate all read
the same. This sorts them and writes docs/QUEST_VERIFICATION_RESULTS.md.

    tools/verify_report.py <path to verify.csv> [-o docs/QUEST_VERIFICATION_RESULTS.md]

Copyright (c) 2026 Bates LLC.  All rights reserved.
"""
import argparse
import csv
import os
import sys
from collections import defaultdict


def classify(row):
    npc = row['npc']
    if row['ok'] == 'ok':
        return 'ok'
    # "standing in X, quest is in Y" is the harness failing, not the data: the teleport did
    # not take. The first full sweep wedged in the Shrine of Ru'Avitau and produced 245 of
    # these in a row. They are not evidence of anything and are counted separately.
    if 'standing in' in row['why']:
        return 'not checked'
    if npc.startswith('qm') or npc.startswith('_') or '???' in npc:
        return 'marker'
    if not npc:
        return 'unnamed'
    return 'absent'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('csv')
    ap.add_argument('-o', '--out', default='docs/QUEST_VERIFICATION_RESULTS.md')
    args = ap.parse_args()

    cols = ['area', 'id', 'ok', 'name', 'npc', 'want_zone', 'want_x', 'want_z',
            'zone', 'x', 'z', 'dist', 'why']
    rows = {}
    with open(args.csv, newline='', encoding='utf-8', errors='replace') as fh:
        for r in csv.DictReader(fh, fieldnames=cols):
            if not r['area'] or r['id'] is None:
                continue
            rows[(r['area'], r['id'])] = r      # a later row wins: --recheck overwrites
    if not rows:
        sys.exit('no rows in ' + args.csv)

    buckets = defaultdict(list)
    for r in rows.values():
        buckets[classify(r)].append(r)

    unchecked = len(buckets['not checked'])
    total = len(rows) - unchecked
    ok = len(buckets['ok'])
    dists = sorted(float(r['dist']) for r in buckets['ok'] if r['dist'])

    out = []
    out.append('# Every quest, checked by standing on it\n')
    out.append('Generated by `tools/verify_report.py` from a sweep of the live client. '
               'How the sweep works, and what a miss does and does not mean, is in '
               '[QUEST_VERIFICATION.md](QUEST_VERIFICATION.md).\n')
    out.append('| | quests |')
    out.append('| --- | --- |')
    out.append(f'| **checked** | {total} |')
    out.append(f'| **NPC found where the guide points** | {ok} ({ok * 100 // max(total,1)}%) |')
    out.append(f'| marker quest (the "NPC" is a door or a ???) | {len(buckets["marker"])} |')
    out.append(f'| NPC not spawned by this server | {len(buckets["absent"])} |')
    out.append(f'| teleport did not take — nothing learned, re-run these | {unchecked} |')
    out.append(f'| no NPC named in the database | {len(buckets["unnamed"])} |')
    if dists:
        mid = dists[len(dists) // 2]
        out.append(f'\nOf the ones found, half were within **{mid:.1f} yalms** of the '
                   f'coordinate the guide gives, and the worst was {dists[-1]:.1f}.\n')

    if unchecked:
        out.append(f'\n## Not checked ({unchecked})\n')
        out.append('The character never arrived, so these rows say nothing about the data. '
                   'Re-run with `--recheck`.\n')

    if buckets['absent']:
        out.append('\n## Not spawned by this server\n')
        out.append('Right coordinate, no NPC standing on it — LandSandBoat implements a subset '
                   'of the game. These are worth re-checking on a server that implements them '
                   'before treating any of them as a data error.\n')
        out.append('| quest | NPC | zone |')
        out.append('| --- | --- | --- |')
        for r in sorted(buckets['absent'], key=lambda r: (int(r['want_zone'] or 0), r['name'])):
            out.append(f'| {r["name"]} | {r["npc"]} | {r["want_zone"]} |')

    if buckets['marker']:
        out.append('\n## Marker quests\n')
        out.append('Started at a `???`, a door or an object rather than by talking to somebody. '
                   'The database carries the server\'s internal name and the client never uses '
                   'it, so these are checked by "is anything standing here" instead.\n')
        out.append('| quest | marker | zone | result |')
        out.append('| --- | --- | --- | --- |')
        for r in sorted(buckets['marker'], key=lambda r: (int(r['want_zone'] or 0), r['name'])):
            out.append(f'| {r["name"]} | `{r["npc"]}` | {r["want_zone"]} | {r["why"]} |')

    text = '\n'.join(out) + '\n'
    os.makedirs(os.path.dirname(args.out) or '.', exist_ok=True)
    open(args.out, 'w', encoding='utf-8').write(text)
    print(f'{total} checked, {ok} found, {len(buckets["absent"])} absent, '
          f'{len(buckets["marker"])} markers, {unchecked} not checked '
          f'-> {args.out}')


if __name__ == '__main__':
    sys.exit(main())
