#!/usr/bin/env python3
"""Vanaguide :: tools/verify_report.py

Turn the ledger into something a person can act on.

Two sources of evidence answer different questions. `npc_list` says where the server will
spawn an NPC — cheap, complete, and available for every quest at once. The in-client sweep
says what was actually standing there when a character stood on the spot — slow, partial, and
the only thing that can speak for a `???` or a door. This writes what they say together, in
the order somebody fixing the data would want to read it.

    tools/verify_report.py [-o docs/QUEST_VERIFICATION_RESULTS.md]

Copyright (c) 2026 Bates LLC.  All rights reserved.
"""
import argparse
import os
import sys

import ledger

ORDER = ['verified', 'server confirmed', 'data error', 'only the client can check this',
         'not on this server', 'nothing to check', 'pending']

BLURB = {
    'verified': 'A character stood on the coordinate and the quest\'s own NPC was loaded and '
                'named there. This is the strongest statement the project can make.',
    'server confirmed': 'The server spawns that NPC, in that zone, within ten yalms of where '
                        'the guide points. Nobody has stood on it yet.',
    'data error': 'The server puts the NPC somewhere the guide does not.',
    'only the client can check this': 'The "NPC" is a `???`, a door or a dig point. It is a '
                                      'real entity with an internal name, and `npc_list` is '
                                      'not a reliable witness for it.',
    'not on this server': 'No NPC of that name exists in this server\'s data at all.',
    'nothing to check': 'The quest script states no place — a mog-house moogle, or no '
                        'location given anywhere.',
    'pending': 'Nobody has looked yet.',
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--db', default=ledger.DB)
    ap.add_argument('-o', '--out', default='docs/QUEST_VERIFICATION_RESULTS.md')
    args = ap.parse_args()

    db = ledger.connect(args.db)
    try:
        rows = db.execute('SELECT * FROM quest_verdict').fetchall()
    except Exception:
        sys.exit('no quest_verdict view — run tools/npc_positions.py first')
    if not rows:
        sys.exit('the ledger is empty — run tools/ledger.py init')

    by = {}
    for r in rows:
        by.setdefault(r['verdict'], []).append(r)
    total = len(rows)
    good = len(by.get('verified', [])) + len(by.get('server confirmed', []))

    out = ['# Every quest, checked\n']
    out.append('Generated by `tools/verify_report.py` from `data/verification.sqlite3`. How '
               'the two checks work, and what a miss does and does not mean, is in '
               '[QUEST_VERIFICATION.md](QUEST_VERIFICATION.md).\n')
    out.append(f'**{good} of {total} quests are confirmed correct** '
               f'({good * 100 // total}%).\n')
    out.append('| | quests | |')
    out.append('| --- | ---: | --- |')
    for v in ORDER:
        if by.get(v):
            out.append(f'| **{v}** | {len(by[v])} | {BLURB[v]} |')

    found = [r for r in by.get('verified', []) if r['dist'] is not None]
    if found:
        d = sorted(r['dist'] for r in found)
        out.append(f'\nOf the ones a character stood on, half were within '
                   f'**{d[len(d) // 2]:.1f} yalms** of the coordinate the guide gives, and '
                   f'the worst was {d[-1]:.1f}.\n')

    # The interesting half of "server confirmed": a character stood there and saw nothing.
    # That is not a bad coordinate -- npc_list has the NPC, at that spot, in that zone -- it is
    # an NPC the server spawns only under a condition a blank character does not meet. Nearly
    # all of them are Crystal War and Abyssea, where the NPC exists only once the storyline
    # has been started.
    looked = [r for r in by.get('server confirmed', []) if r['client'] == 'absent']
    if looked:
        out.append(f'\n## Confirmed by the server, absent in the client ({len(looked)})\n')
        out.append('`npc_list` places the NPC exactly where the guide points, and a character '
                   'standing on the spot saw nothing loaded. That is a spawn condition, not a '
                   'wrong coordinate: these NPCs appear once the storyline that owns them has '
                   'begun, and the character sweeping has begun nothing.\n')
        out.append('| quest | NPC | zone |')
        out.append('| --- | --- | ---: |')
        for r in sorted(looked, key=lambda r: (r['area'], r['id'])):
            out.append(f'| {r["name"]} | `{r["npc"]}` | {r["zone"]} |')

    for v in ('data error', 'not on this server', 'nothing to check',
              'only the client can check this'):
        if not by.get(v):
            continue
        out.append(f'\n## {v.capitalize()} ({len(by[v])})\n')
        out.append(BLURB[v] + '\n')
        out.append('| quest | NPC | zone | |')
        out.append('| --- | --- | ---: | --- |')
        for r in sorted(by[v], key=lambda r: (r['area'], r['id'])):
            out.append(f'| {r["name"]} | `{r["npc"] or "—"}` | {r["zone"] or "—"} | '
                       f'{r["why"] or r["server"]} |')

    text = '\n'.join(out) + '\n'
    os.makedirs(os.path.dirname(args.out) or '.', exist_ok=True)
    open(args.out, 'w', encoding='utf-8').write(text)
    print(f'{good}/{total} confirmed -> {args.out}')


if __name__ == '__main__':
    sys.exit(main())
